### ISSUE TITLE
Url illegel 

### ISSUE THREAD

**Issue by ffashion** [PixelOS-Devices-old/device_oneplus_sm8550-common#1]
https://github.com/AOSPA/proprietary_vendor_qcom_common in [lineage.dependencies](https://github.com/PixelOS-Devices/device_oneplus_sm8550-common/blob/fourteen/lineage.dependencies)  is  illegel . how can i get this repo ?

**Comment by hridaya2004** [comment]
lineage.dependencies is not used here.

**Comment by ffashion** [comment]
> lineage.dependencies is not used here.
> 

i know that . i tring to use this repo to compile lineage . so i failed . so question is： do we have any build guide for lineage or pixelsos . i found we release a pixelos package  but lineage didnot. can we build lineage successful ？

**Comment by hridaya2004** [comment]
> > lineage.dependencies is not used here.
> 
> i know that . i tring to use this repo to compile lineage . so i failed . so question is： do we have any build guide for lineage or pixelsos . i found we release a pixelos package but lineage didnot. can we build lineage successful ？

This is NOT LineageOS!
